#!/usr/bin/env ruby

root = `git rev-parse --show-toplevel`.strip
environments = Dir.glob("#{root}/config/deploy/*")
keep_branches = environments.map{ |b| b.split("/").pop}.map{|b| b.split(".")[0]}
keep_branches << 'master'
remotes=`git remote show`.split("\n")
`git checkout master`
`git pull`

remotes.each do |remote|
  `git fetch #{remote}`
  `git remote prune #{remote}`
  branches = []
  `git branch -r --merged`.split("\n").each do |branch|
    branches << branch.strip.gsub("#{remote}/",'')
  end
  branches -= keep_branches
  branches.each do |branch|
    `git push #{remote} :#{branch}` unless branch.match("/") || branch.match("->")
  end
  `git remote prune #{remote}`
end
branches=[]
`git branch --merged`.split("\n").each do |branch|
  branches << branch.strip
end
branches -= keep_branches
branches.each do |branch|
  `git branch -D #{branch}` unless branch.match('\*') || branch.match("->")
end
