#!/bin/bash
set -e

git fsck --full --no-reflogs --unreachable --lost-found |\
  grep -v blob |\
  awk '{sub(/unreachable\ commit\ /,"");print}' |\
  xargs -n 1 git log -n 1 --pretty=oneline

echo "git checkout -b <branch> <sha>"